keywords: 
author: Mantas Marcinkus,mantas.marcinkus.bio@gmail.com
description: My experience and insights gained during my short developement carrer
aboutme: I'm Mantas Marcinkus, a software developer in London, United Kingdom
goals: In a quest of understanding how do I see myself in five years time
avatar: https://scontent-lhr3-1.xx.fbcdn.net/v/t1.0-9/12744206_1300936263253589_159041173686036870_n.jpg?oh=16c33ac13f630f817cf3690065f9bb74&oe=59495714

# Comment
duoshuo:
disqus:
